info:
  namespace: warriorland_halloween

items:
  hunter_mask:
    name: "&6&lMaska nočního lovce &8[Halloween 2026]"
    lore:
      - "&7Limitovaná Halloween odměna."
      - "&7Připomínka eventu WarriorLand 2026."
    material: CARVED_PUMPKIN
    graphics:
      texture: item/hunter_mask

  cursed_talisman:
    name: "&5&lProkletý talisman &8[2026]"
    lore:
      - "&7Relikvie vysokého prokletí."
      - "&7Odemčená až na vyšší úrovni prokletí."
    material: NETHER_STAR
    graphics:
      texture: item/cursed_talisman

  halloween_token:
    name: "&c&lHalloween 2026"
    lore:
      - "&7Jedinečná památka."
      - "&8Po skončení eventu už nebude běžně dostupná."
    material: NAME_TAG
    graphics:
      texture: item/halloween_token

  cursed_candy:
    name: "&6&lProkleté cukroví &8[Halloween 2026]"
    lore:
      - "&7Padá ze speciálních Halloween mobů."
      - "&7Po snězení tě na chvíli poznačí prokletí."
    material: PUMPKIN_PIE
    graphics:
      texture: item/cursed_candy
    consumable:
      nutrition: 1
      saturation: 0.2
