info:
  namespace: warriorland_halloween

minecraft_lang_overwrite:
  halloween_sounds:
    entries:
      sound.haunted_theme: "Halloween ambient theme"
      sound.event_sting: "Halloween event sting"
    languages:
      - ALL

sounds:
  haunted_theme:
    path: haunted_theme
    settings:
      subtitle: sound.haunted_theme
      stream: true
      volume: 1.0
      pitch: 1.0
  event_sting:
    path: event_sting
    settings:
      subtitle: sound.event_sting
      volume: 1.0
      pitch: 1.0
